/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chandan' at '9/4/16 12:24 AM' with Gradle 2.10
 *
 * @author chandan, @date 9/4/16 12:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
